### PR TITLE
update rn60.x

### PR DESCRIPTION
**Pull request by GaspardC**

### CODE REVIEW

**Comment by mars-lan** [comment]
@christophermark please also merge this in after fixing the conflict. Otherwise it won't build on RN 0.60+

**Comment by christophermark** [comment]
I've been meaning to get around to this - haven't had much time to pull down and take a look.

@mars-lan @GaspardC have you tested to confirm this works on a React Native 0.60+ app?

I personally haven't made the jump to 0.60, but that shouldn't mean we can't merge this in on a different semver major version.

**Comment by mars-lan** [comment]
@christophermark Here's a separate PR that's been fully tested on RN 0.60+ and has no merge conflict: https://github.com/robinpowered/react-native-screen-brightness/pull/37

**Comment by christophermark** [comment]
@GaspardC thanks for getting the ball rolling on this. @mars-lan picked up where you started and we ended up merging #37.

I'm closing this as our [new version](https://github.com/robinpowered/react-native-screen-brightness/releases/tag/v2.0.0-alpha) should work. If not, feel free to submit any changes needed to get things working and we'll do our best to merge and release quickly

**Pull request closed without merging**
